### PR TITLE
Feature master test coverage

### PR DESCRIPTION
**Pull request by Klemele**

### CODE REVIEW

**Review by RiceBowlJr — DISMISSED** [review]
OK for me, don't understand much but didn't see any typo or any nonsense.

**Comment by RiceBowlJr** [comment]
@Klemele [sign your commits](https://help.github.com/articles/about-gpg/) cf last message.

**Review by RiceBowlJr — APPROVED** [review]
LGTM

**Review by RiceBowlJr — COMMENTED** [review]
@michaelchiche any comment on that ? :smiley:

**Comment by michaelchiche** [comment]
LGTM

**Pull request merged**
